export const ENUM_LABELS: Record<string, string> = {
  NotStarted: "Not started",
  InProgress: "In progress",
  Blocked: "Blocked",
  Completed: "Completed",
  Planning: "Planning",
  Active: "Active",
  Archived: "Archived",
  Prospect: "Prospect",
  Engaged: "Engaged",
  Contracted: "Contracted",
  ContractSigned: "Contract signed",
  Onboarded: "Onboarded",
  PostEvent: "Post-event",
  NotRequested: "Not requested",
  Pending: "Pending",
  Granted: "Granted",
  PartiallyGranted: "Partially granted",
  Declined: "Declined",
  Withdrawn: "Withdrawn",
  Identified: "Identified",
  Invited: "Invited",
  Confirmed: "Confirmed",
  Briefed: "Briefed",
  Ready: "Ready",
  Attended: "Attended",
  Thanked: "Thanked",
  StandAlone: "Stand-alone",
  Fireside: "Fireside chat",
  Panel: "Panel",
  Presentation: "Presentation",
  Breakaway: "Breakaway",
  Break: "Break",
  Intermission: "Intermission",
  Proposed: "Proposed",
  Tentative: "Tentative",
  Speaker: "Speaker",
  Panelist: "Panelist",
  Moderator: "Moderator",
  Chair: "Chair",
  Admin: "Admin",
  Curator: "Curator",
  Finance: "Finance",
  PartnerLead: "Partner lead",
  SpeakerLead: "Speaker lead",
  Ops: "Operations",
  PressManager: "Press manager",
  Advisor: "Advisor",
  Client: "Client",
  Internal: "Internal",
  External: "External",
  Email: "Email",
  Phone: "Phone",
  WhatsApp: "WhatsApp",
  Origination: "Origination",
  Sponsorships: "Sponsorships",
  DelegatePasses: "Delegate passes",
  Operations: "Operations",
  Marketing: "Marketing",
  Venue: "Venue",
  Catering: "Catering",
  AV: "AV & Production",
  Travel: "Travel",
  Contingency: "Contingency",
  Platinum: "Platinum",
  Gold: "Gold",
  Silver: "Silver",
  Bronze: "Bronze",
  CredibilityOnly: "Credibility only",
  InKind: "In-kind",
  // Service provider categories
  VenueHotel: "Venue / Hotel",
  Sound: "Sound",
  Stage: "Stage",
  Lighting: "Lighting",
  AVStreaming: "AV & Streaming",
  Power: "Power",
  InternetIT: "Internet & IT",
  Graphics: "Graphics",
  PrintSignage: "Print & Signage",
  PhotoVideo: "Photo & Video",
  MediaPR: "Media & PR",
  Entertainment: "Entertainment",
  FurnitureDecor: "Furniture & Décor",
  Gifting: "Gifting",
  TravelLogistics: "Travel & Logistics",
  Health: "Health",
  Security: "Security",
  ProtocolStaffing: "Protocol & Staffing",
  Interpretation: "Interpretation",
  Payments: "Payments",
  Insurance: "Insurance",
  ExhibitionBuild: "Exhibition Build",
  Other: "Other",
  // Procurement statuses
  Shortlisted: "Shortlisted",
  Quoted: "Quoted",
  Paid: "Paid",
  EarlyBird: "Early Bird",
  Standard: "Standard",
  Late: "Late",
  FreeSponsor: "Sponsor Comp",
  FreeComp: "Complimentary",
  Press: "Press Pass",
  Official: "Official Pass",
  VIP: "VIP Pass",
  OnHold: "On hold",
  // Negotiation (partner engagement)
  Negotiation: "Negotiation",
  Financial: "Financial",
  Yes: "Yes",
  No: "No",
  Partial: "Partial",
};

export function label(key: string | null | undefined): string {
  if (!key) return "—";
  return ENUM_LABELS[key] ?? key;
}
