import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import meRouter from "./me";
import conveningsRouter from "./convenings";
import partnersRouter from "./partners";
import engagementsRouter from "./engagements";
import speakersRouter from "./speakers";
import speakerEngagementsRouter from "./speaker-engagements";
import consentsRouter from "./consents";
import budgetsRouter from "./budgets";
import workstreamsRouter from "./workstreams";
import tasksRouter from "./tasks";
import analyticsRouter from "./analytics";
import usersRouter from "./users";
import sessionsRouter from "./sessions";
import serviceProvidersRouter from "./service-providers";
import dealRoomRouter from "./deal-room";
import outcomesRouter from "./outcomes";
import documentsRouter from "./documents";
import storageRouter from "./storage";
import delegatesRouter from "./delegates";
import exhibitionRouter from "./exhibition";
import sponsorshipsRouter from "./sponsorships";
import passTypeConfigsRouter from "./pass-type-configs";
import teamRouter from "./team";
import auditRouter from "./audit";
import trashRouter from "./trash";
import invitesRouter from "./invites";
import setupRouter from "./setup";
import accessRequestsRouter from "./access-requests";
import milestonesRouter from "./milestones";
import taskAttachmentsRouter from "./taskAttachments";
import sheetsRouter from "./sheets";
import pillarsRouter from "./pillars";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(meRouter);
router.use(conveningsRouter);
router.use(partnersRouter);
router.use(engagementsRouter);
router.use(speakersRouter);
router.use(speakerEngagementsRouter);
router.use(consentsRouter);
router.use(budgetsRouter);
router.use(workstreamsRouter);
router.use(tasksRouter);
router.use(sessionsRouter);
router.use(serviceProvidersRouter);
router.use(dealRoomRouter);
router.use(outcomesRouter);
router.use(documentsRouter);
router.use(storageRouter);
router.use(delegatesRouter);
router.use(exhibitionRouter);
router.use(sponsorshipsRouter);
router.use(passTypeConfigsRouter);
router.use(teamRouter);
router.use(auditRouter);
router.use(trashRouter);
router.use(invitesRouter);
router.use(setupRouter);
router.use(accessRequestsRouter);
router.use(milestonesRouter);
router.use(taskAttachmentsRouter);
router.use(sheetsRouter);
router.use(pillarsRouter);
router.use(analyticsRouter);
router.use(usersRouter);

export default router;
