// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/style-guide/StyleGuide.tsx": () => import("../components/mockups/style-guide/StyleGuide.tsx")
};
